import { Languages } from '../characterCreation.types';

export const languages: Languages = {
  Elf: ['Celestial', 'Draconic', 'Gnoll', 'Gnome', 'Goblin', 'Orc', 'Sylvan'],
  Human: [
    'Abyssal',
    'Aklo',
    'Aquan',
    'Auran',
    'Celestial',
    'Draconic',
    'Dwarven',
    'Elven',
    'Ignan',
    'Infernal',
    'Giant',
    'Gnome',
    'Goblin',
    'Halfling',
    'Orc',
    'Sylvan',
    'Terran',
    'Undercommon',
  ],
  'Half-Elf': [
    'Abyssal',
    'Aklo',
    'Aquan',
    'Auran',
    'Celestial',
    'Draconic',
    'Dwarven',
    'Ignan',
    'Infernal',
    'Giant',
    'Gnome',
    'Goblin',
    'Halfling',
    'Orc',
    'Sylvan',
    'Terran',
    'Undercommon',
  ],
  Dwarf: ['Giant', 'Gnome', 'Goblin', 'Orc', 'Terran', 'Undercommon'],
  'Half-Orc': [
    'Abyssal',
    'Aklo',
    'Aquan',
    'Auran',
    'Celestial',
    'Draconic',
    'Dwarven',
    'Ignan',
    'Infernal',
    'Giant',
    'Gnome',
    'Goblin',
    'Halfling',
    'Orc',
    'Sylvan',
    'Terran',
    'Undercommon',
  ],
  Halfling: ['Dwarven', 'Elven', 'Gnome', 'Goblin'],
};
